### ISSUE TITLE
Нужен рефакторинг в функции меню.

### ISSUE THREAD

**Issue by schdub** [xojld0/DDOS_master#1]
Привет. Не смог пройти мимо кода типа:

		switch(choose) {
		case 0:
			cout << "0) Белый     <-\n";
			cout << "1) Зелёный     \n";
			cout << "2) Синий       \n";
			cout << "3) Красный     \n";
			cout << "4) Розовый     \n";
			break;
		case 1:
			cout << "0) Белый       \n";
			cout << "1) Зелёный   <-\n";
			cout << "2) Синий       \n";
			cout << "3) Красный     \n";
			cout << "4) Розовый     \n";
			break;
		case 2:
			cout << "0) Белый       \n";
			cout << "1) Зелёный     \n";
			cout << "2) Синий     <-\n";
			cout << "3) Красный     \n";
			cout << "4) Розовый     \n";
			break;
		case 3:
			cout << "0) Белый       \n";
			cout << "1) Зелёный     \n";
			cout << "2) Синий       \n";
			cout << "3) Красный   <-\n";
			cout << "4) Розовый     \n";
			break;
		case 4:
			cout << "0) Белый       \n";
			cout << "1) Зелёный     \n";
			cout << "2) Синий       \n";
			cout << "3) Красный     \n";
			cout << "4) Розовый   <-\n";
			break;
		default:
			cout << "0) Белый     \n";
			cout << "1) Зелёный   \n";
			cout << "2) Синий       \n";
			cout << "3) Красный     \n";
			cout << "4) Розовый   \n";
			break;
		}

Его можно заменить простым циклом:

        const char* colors[] = { "Белый  ", "Зелёный", "Синий  ", "Красный", "Розовый" };
        for (int i = 0; i < sizeof(colors)/sizeof(*colors); ++i) {
            std::cout << i << ") " << colors[i] << "     " << (choose == i ? "<-\n" : "  \n");
        }

PS: не смог сделать PR, т.к. какие-то траблы с кодировками, при создании пул-реквеста.

**Comment by xojld0** [comment]
Я новичёк, спасибо за помощь. Код исправлю.
